SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET LINESIZE 1000
SET PAGESIZE 0
SET TRIM ON
SET TRIMSPOOL ON
SET ECHO OFF
SET FEEDBACK OFF
 SELECT DBMS_SQLTUNE.report_sql_monitor(  sql_id       => '&sql_id',  report_level => 'ALL') from dual;